import 'dart:io';

import 'package:build/build.dart';
import 'package:build_test/build_test.dart';
import 'package:coap/builder.dart';
import 'package:test/test.dart';

void main() {
  final builder = configBuilder(const BuilderOptions({}));

  group('configBuilder', () {
    group('buildExtensions', () {
      test('maps .yaml to .dart', () {
        expect(builder.buildExtensions, equals({'.yaml': ['.dart']}));
      });
    });

    group('generateClassName', () {
      test('single word', () {
        expect(generateClassName('coap_config.yaml'), 'CoapConfig');
      });

      test('multiple underscores', () {
        expect(generateClassName('coap_config_all.yaml'), 'CoapConfigAll');
      });

      test('already capitalized segments', () {
        expect(generateClassName('coap_config_default.yaml'), 'CoapConfigDefault');
      });
    });

    group('build output', () {
      test('generates Dart class from minimal config with version key', () async {
        await testBuilder(
          builder,
          {
            'coap|lib/coap_config.yaml': '''
version: 1
''',
          },
          outputs: {
            'coap|lib/coap_config.dart': decodedMatches(
              allOf(
                contains("// GENERATED CODE, do not edit this file."),
                contains("class CoapConfig extends DefaultCoapConfig {"),
                contains("int get version => 1;"),
              ),
            ),
          },
        );
      });

      test('generates int getters', () async {
        await testBuilder(
          builder,
          {
            'coap|lib/coap_config.yaml': '''
version: 1
defaultPort: 5683
maxRetransmit: 4
''',
          },
          outputs: {
            'coap|lib/coap_config.dart': decodedMatches(
              allOf(
                contains('int get defaultPort => 5683;'),
                contains('int get maxRetransmit => 4;'),
              ),
            ),
          },
        );
      });

      test('generates double getters', () async {
        await testBuilder(
          builder,
          {
            'coap|lib/coap_config.yaml': '''
version: 1
ackRandomFactor: 1.5
ackTimeoutScale: 2.0
''',
          },
          outputs: {
            'coap|lib/coap_config.dart': decodedMatches(
              allOf(
                contains('double get ackRandomFactor => 1.5;'),
                contains('double get ackTimeoutScale => 2.0;'),
              ),
            ),
          },
        );
      });

      test('generates bool getters', () async {
        await testBuilder(
          builder,
          {
            'coap|lib/coap_config.yaml': '''
version: 1
useRandomIDStart: false
''',
          },
          outputs: {
            'coap|lib/coap_config.dart': decodedMatches(
              contains('bool get useRandomIDStart => false;'),
            ),
          },
        );
      });

      test('generates string getters', () async {
        await testBuilder(
          builder,
          {
            'coap|lib/coap_config.yaml': '''
version: 1
deduplicator: "MarkAndSweep"
''',
          },
          outputs: {
            'coap|lib/coap_config.dart': decodedMatches(
              contains("String get deduplicator => 'MarkAndSweep';"),
            ),
          },
        );
      });

      test('generates nested YAML keys with camelCase names', () async {
        await testBuilder(
          builder,
          {
            'coap|lib/coap_config.yaml': '''
version: 1
dtls:
  verify: false
  withTrustedRoots: true
''',
          },
          outputs: {
            'coap|lib/coap_config.dart': decodedMatches(
              allOf(
                contains('bool get dtlsVerify => false;'),
                contains('bool get dtlsWithTrustedRoots => true;'),
              ),
            ),
          },
        );
      });

      test('skips null values', () async {
        await testBuilder(
          builder,
          {
            'coap|lib/coap_config.yaml': '''
version: 1
dtls:
  ciphers: null
''',
          },
          outputs: {
            'coap|lib/coap_config.dart': decodedMatches(
              isNot(contains('dtlsCiphers')),
            ),
          },
        );
      });

      test('generates dtlsBackend getter with DtlsBackend prefix', () async {
        await testBuilder(
          builder,
          {
            'coap|lib/coap_config.yaml': '''
version: 1
dtlsBackend: openSsl
''',
          },
          outputs: {
            'coap|lib/coap_config.dart': decodedMatches(
              contains('DtlsBackend? get dtlsBackend => DtlsBackend.openSsl;'),
            ),
          },
        );
      });

      test('non-matching filename is ignored and produces no output', () async {
        await testBuilder(
          builder,
          {
            'coap|lib/other_config.yaml': '''
version: 1
defaultPort: 5683
''',
          },
          outputs: {},
        );
      });

      test('generates class name from multi-part filename', () async {
        await testBuilder(
          builder,
          {
            'coap|lib/coap_config_custom.yaml': '''
version: 1
''',
          },
          outputs: {
            'coap|lib/coap_config_custom.dart': decodedMatches(
              contains('class CoapConfigCustom extends DefaultCoapConfig {'),
            ),
          },
        );
      });

      test('includes import of package:coap/coap.dart', () async {
        await testBuilder(
          builder,
          {
            'coap|lib/coap_config.yaml': '''
version: 1
''',
          },
          outputs: {
            'coap|lib/coap_config.dart': decodedMatches(
              contains("import 'package:coap/coap.dart';"),
            ),
          },
        );
      });

      test('throws when version key is missing', () async {
        final result = await testBuilder(
          builder,
          {
            'coap|lib/coap_config.yaml': '''
defaultPort: 5683
''',
          },
          outputs: {},
        );
        expect(result.succeeded, isFalse);
        expect(
          result.errors.any((e) => e.contains('version')),
          isTrue,
        );
      });
    });

    group('example config', () {
      test(
        'example/config/coap_config.yaml generates example/config/coap_config.dart',
        () async {
          final yamlContent = await File(
            'example/config/coap_config.yaml',
          ).readAsString();
          final dartContent = await File(
            'example/config/coap_config.dart',
          ).readAsString();

          await testBuilder(
            builder,
            {'coap|example/config/coap_config.yaml': yamlContent},
            outputs: {
              'coap|example/config/coap_config.dart': dartContent,
            },
          );
        },
      );
    });
  });
}
